[package]
name = "kitchen-lights"
version = "0.1.0"
authors = ["decentninja <encrpt.wave@gmail.com>"]
edition = "2018"

[dependencies]
philipshue = "0.3.2"
byteorder = "1.3.1"
chrono = "0.4.6"
ron = "0.5.1"
serde = "1.0.92"
failure = "0.1.5"
rppal = "0.11.2"
